### ISSUE TITLE
dfs와 bfs의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by Kim-AYoung** [Kim-AYoung/dev-study#1]
## 어떤 상황에서 dfs, bfs를 사용해야할까요?

백준의 ~ 문제에서 dfs, bfs 둘 중에 어떤 알고리즘을 사용할지 고민이 됩니다.
도와주세요!

**Comment by blacklabf** [comment]
dfs는 가지치기로서 완전탐색을 하다가 백트래킹 요소가 있으면 dfs를 사용하고
bfs는 전체 탐색을 하면서 중간에 구현해야 하는 게 있을 때 종종 씁니다!

**Comment by blacklabf** [comment]
d와 b의 차이입니다.!
눈을 똥그랗게 뜨고  봐주세요!
