### ISSUE TITLE
프로새스 생성 방법 중 fork 기법에 대해 의문이 생겼습니다! 

### ISSUE THREAD

**Issue by blacklabf** [Kim-AYoung/dev-study#2]
## 프로세스 생성 방법에 대한 의문

프로세스 생성할 때 부모 프로세스가 자식 프로세스를 복제해서 생성하는 기법(fork)가 있다고 하는데 어떤 경우에 자식 프로세스를 복제하는 건가요?
exec를 통해 자식의 메모리 공간을 다른 프로그램으로 어차피 바꿔서 본인의 코드를 실행하는데 왜 굳이 부모가 복제해서 생성하는 건지 잘 이해가 안 갑니다!

**Comment by Kim-AYoung** [comment]
이와 비슷한 내용이 명세된 블로그가 있어서 제 의견을 약간 첨가하여 정리해보았습니다. 

첫번째로 자식 프로세스 생성시, 굉장히 멀리 있는 보조 기억장치에서부터 새로운 프로그램을 로드하여 프로세스를 생성하는 것보다 부모 프로세스를 그대로 복제하는 것이 프로세스 생성 비용이 절감되는 것 같습니다. (기존 부모 프로세스가 실행하던 코드에 자식 프로세스가 실행할 코드도 존재하기 때문에 그대로 복제해서 사용할 수 있음.)
또한 자식 프로세스 복제 후, 자식 / 부모 프로세스가 리소스를 공유하다가 한 프로세스에서 수정이 발생되면 그때서야 자식 프로세스가 부모 프로세스의 메모리를 복사하여 사용한다고도 합니다.

두번째로, 부모 프로세스에서 파생된 자식 프로세스들이 부모가 종료되면 같이 종료되기 때문에 관리 측면에서도 용이합니다.

> Reference
[왜 프로세스를 생성할 때 fork()를 사용할까?](https://wslog.dev/fork-exec)

**Comment by blacklabf** [comment]
좋은 설명 감사합니다. 알려주신 내용이랑 헷갈렸던 부분을 조금 더 정리해보았습니다!

![image](https://github.com/Kim-AYoung/dev-study/assets/108640460/36618841-7d2f-4945-83f5-1b013d89dd61)

보조메모리에 있던 프로그램에 실행과 관련된 코드가 있으면 RAM으로 이동을 함.  -> 이 떄, 많은 비용이 발생함
보조메모리(디스크)에서 프로그램을 RAM으로 불러오는 순간 프로세스가 된다.
RAM에서 프로세스가 준비상태가 되고 CPU 스케줄링에 의해 CPU를 할당 받으면 CPU로 옮겨짐
그 때, 그 프로세스에 fork() 명령어가 있으면 자식 프로세스를 만드는데 이 때 부모의 같은 리소스를 공유함 (복제 비용이 들기 때문에 최대한 복제를 미룸) 
그러다가 자식 프로세스의 변경이 발생하면 (exec()) 그 때서야, 복제가 시작되고 변경이 이루어짐 

------------------------------------------------------------------------------------------
그럼, 왜 굳이 fork()를 해서 프로세스를 만드는지에 대한 답변은
보조 메모리에서 RAM으로 가져올 때 많은 비용이 드는데 자식 프로세스를 만들면 RAM에서 바로 만들 수 있기 때문에 비용이 절감된다.
