### ISSUE TITLE
final이 아닌 field를 동기화 대상으로 삼으면 인텔리제이에서는 왜 경고를 띄우나?

### ISSUE THREAD

**Issue by Kim-AYoung** [Kim-AYoung/dev-study#3]
# final이 아닌 field를 동기화 대상으로 삼으면 인텔리제이에서는 경고를 띄움.
예제 코드는 다음과 같음.
```java
public class Counter {
  private Count count;

  public setCount(Count count) {
    this.count = count;
  }

  public processCount() {
    synchronized(count) {
      // process using count field...       // intellij warning here   
    }
  } 
}
```

**Comment by Kim-AYoung** [comment]
synchronized block 내에서 실행되고 있는 스레드가 중간에 count 변수를 수정하게 될 경우, 해당 스레드의 동기화 대상(이전의 count 참조)과 다른 스레드의 동기화 대상(변경된 count 참조)이 다르기 때문에 의도치않게 두 스레드가 동시에 실행된다. 
이러면 동기화 이슈가 발생하므로, **synchronized block에서 final이 아닌 field로 동기화하지않기!**

**Comment by blacklabf** [comment]
LGTM 👍
