### ISSUE TITLE
메인 스레드에서 실행한 또다른 스레드가 메인 스레드가 종료되면 같이 종료됩니다.

### ISSUE THREAD

**Issue by Kim-AYoung** [Kim-AYoung/dev-study#4]
## 메인 스레드에서 실행한 또다른 스레드가 메인 스레드가 종료되면 같이 종료됩니다.
이유는 무엇일까요? 같이 종료되지 않도록 설정할 수 있을까요?

**Comment by Kim-AYoung** [comment]
해당 스레드는 데몬 스레드이기 때문입니다.
메인 스레드가 종료될 떄 같이 종료되지 않도록하려면, 다음과 같이 유저 스레드로 설정하면 됩니다.
```java
thread.setDaemon(false);
thread.start();
```
다음은 유저 스레드와 데몬 스레드의 차이입니다.
# User Thread vs Daemon Thread

---

- 유저 스레드
    - 특별히 데몬 스레드로 설정하지 않은 스레드로서, 일반적으로 생성해서 사용되는 스레드이다.
    - JVM은 모든 유저 스레드가 종료될 때까지, 프로그램을 실행한다.
- 데몬 스레드
    - 백그라운드에서 동작하는 스레드이다.
    - JVM은 모든 유저 스레드가 종료되면, 데몬 스레드를 강제로 종료한다.
    - 주로 메인 스레드나 다른 유저 스레드의 보조 역할을 수행하거나, 특정 작업을 주기적으로 처리하는 스레드 등에 사용된다.
    - 모든 스레드의 생성과 종료를 직접 관리하지 않을 수도 있다.
    - 데몬 스레드의 우선 순위는 낮으나 조정 가능하다.

**Comment by blacklabf** [comment]
감사합니다! 이해가 잘 돼요!
