### ISSUE TITLE
web architecture 101 일부를 정리해서 올렸는데 피드백 부탁드립니다~

### ISSUE THREAD

**Issue by blacklabf** [Kim-AYoung/dev-study#5]

**Comment by Kim-AYoung** [comment]
정리해주신 부분 확인했습니다! 제가 가지고있는 지식내에서 정확한 내용인 것 같습니다!

저도 소영님 덕분에 웹 아키텍처의 흐름에 대해 정리할 수 있는 좋은 시간을 가졌습니다.
추후 정리내용들은 저도 궁금한 내용들이라 나중에 정리하시면 알려주세요 😃
